# Generated by Django 3.0.6 on 2020-05-17 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='プロジェクトネーム')),
                ('type', models.CharField(choices=[('web', 'web'), ('app', 'app')], max_length=50, verbose_name='プロジェクトタイプ')),
                ('description', models.CharField(blank=True, max_length=1024, verbose_name='詳細')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='最近の修正時間')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作った時間')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作った人')),
            ],
        ),
    ]
