# Generated by Django 3.0.6 on 2020-05-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('host', models.CharField(max_length=1024, verbose_name='hostアドレス')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='詳細')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_list', to='apitest.Project', verbose_name='所属プロジェクト')),
            ],
        ),
    ]
