# Generated by Django 3.0.6 on 2020-05-30 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apitest', '0003_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRunRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='リクエストurl')),
                ('http_method', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10, verbose_name='リクエストメソッド')),
                ('data', models.TextField(null=True, verbose_name='提出データ')),
                ('headers', models.TextField(null=True, verbose_name='提出header')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='実行時間')),
                ('return_code', models.CharField(max_length=10, verbose_name='レスポンスcode')),
                ('return_content', models.TextField(null=True, verbose_name='レスポンス内容')),
                ('api', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.Api', verbose_name='関連API')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
    ]
